In [17]:
from functools import reduce
import numpy as np
import math as m
pi = m.pi
a1 = np.array([2, 1, 0 ,0])
a2 = np.array([0, 0, 1 ,1])
a3 = np.array([1,1,0,0])
a4 = np.array([1,1,1,0])

angle_a1_a2 = np.arccos( reduce(lambda x, y: x+y, a1 * a2) / (np.sqrt(reduce(lambda x, y: x + y , map(lambda k: k ** 2, a1))) * np.sqrt(reduce(lambda x, y: x + y , map(lambda k: k ** 2, a2))))) * 180/pi
angle_a1_a3 = np.arccos( reduce(lambda x, y: x+y, a1 * a3) / (np.sqrt(reduce(lambda x, y: x + y , map(lambda k: k ** 2, a1))) * np.sqrt(reduce(lambda x, y: x + y , map(lambda k: k ** 2, a3))))) * 180/pi
angle_a1_a4 = np.arccos( reduce(lambda x, y: x+y, a1 * a4) / (np.sqrt(reduce(lambda x, y: x + y , map(lambda k: k ** 2, a1))) * np.sqrt(reduce(lambda x, y: x + y , map(lambda k: k ** 2, a4))))) * 180/pi
angle_a2_a3 = np.arccos( reduce(lambda x, y: x+y, a2 * a3) / (np.sqrt(reduce(lambda x, y: x + y , map(lambda k: k ** 2, a2))) * np.sqrt(reduce(lambda x, y: x + y , map(lambda k: k ** 2, a3))))) * 180/pi
angle_a2_a4 = np.arccos( reduce(lambda x, y: x+y, a2 * a4) / (np.sqrt(reduce(lambda x, y: x + y , map(lambda k: k ** 2, a2))) * np.sqrt(reduce(lambda x, y: x + y , map(lambda k: k ** 2, a4))))) * 180/pi
angle_a3_a4 = np.arccos( reduce(lambda x, y: x+y, a3 * a4) / (np.sqrt(reduce(lambda x, y: x + y , map(lambda k: k ** 2, a3))) * np.sqrt(reduce(lambda x, y: x + y , map(lambda k: k ** 2, a4))))) * 180/pi

print(angle_a1_a2)
print(angle_a1_a3)
print(angle_a1_a4)
print(angle_a2_a3)
print(angle_a2_a4)
print(angle_a3_a4)

90.0
18.434948822922017
39.23152048359225
90.0
65.90515744788931
35.26438968275467


In [18]:
# Span of a vector: set of all the vectors.
# span(v1, v2, v3....vn) = {c1v1,+c2v2.... CnVn| Ci belongs to R}




In [19]:
# Two dimensional numpy array declaration
from numpy import array
data = [[11, 22],
       [33, 44],
       [55, 66]]
data = array(data)
print(data)
print(type(data))

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


In [29]:
# numpy array indexing
# 1. One dimensional indexing.
data = array([11, 22, 33, 44, 55])
print(data[0])
print(data[3])
print(data[-3:])

11
44
[33 44 55]


In [37]:
# Two dimensional indexing
data = array([
    [11,22],
    [33,44],
    [55, 66]
])
print(data[0,0])
print(data[0,1])

11
22


In [46]:
# Array slicing
# 1. One dimensional slicing
data = array([11, 22, 33, 44, 55])
print(data[-3:-2])

[33]


In [50]:
# Two dimensional slicing
data = array([
    [11, 22, 33],
    [44, 55, 66],
    [77, 88, 99]
])
X, Y = data[:,-1], data[:,:-1]
print(data[1:, 1:2])

print(X) 
print(Y)

[[55]
 [88]]
[33 66 99]
[[11 22]
 [44 55]
 [77 88]]


In [66]:
# Matrix 
# Diagnoal matrix: whose non-diagnoal elements are zero.
# Identity matrix: whose non-diagnonal elements are 0 and diagnoal 
# Matrix addition: 
    # Not all matrix can be added together , Only those matrix that have same dimensions are able to be added together.
    # The resultant of the matrix addition are always equals to the dimension of the child components.
A = array([
    [3,2],
    [0,3]
])

B = array([
    [4, -2],
    [2, -3]
])
res = A * B
print(res)
    
 
    

[[12 -4]
 [ 0 -9]]


In [67]:
# Hadamard Product is the element by element multiplcation among two metrics.

K = array([
    [3,2],
    [0,3]
])

J = array([
    [4, -2],
    [2, -3]
])

mul = K * J
print(mul)
# Whereas  Matrix multiplication of two matrix A and B is only possible when no of columns in A should be equal to the number of row in B. In other words if you have two matrics A and B with the dimensions $\(a_1, a_2) , (b_1, b_2)$
mul = K.dot(J)
print(mul)

[[12 -4]
 [ 0 -9]]
[[ 16 -12]
 [  6  -9]]


In [75]:
# Transponse of matrix:
KT = K.T
JT = J.T

transpose_KJ = KT.dot(JT)
print(transpose_KJ)



[[12  6]
 [ 2 -5]]


In [76]:
# what is not allowed ??:
# 3 X 3 matrix
A = array([
    [2, 3, 4],
    [4, 5, 6],
    [9 , 8, 9]
])
# 2 X 3 matrix
B = array([
    [4, 5, 6]
    [7, 8, 9]
])

res = A* B
# or 
res = A.dot(B)


TypeError: list indices must be integers or slices, not tuple

In [86]:
from numpy import linalg
X = array([
    [4, 2, 5],
    [3, 2, 8],
    [5, 2, 9]
])
inv_X = linalg.inv(X)
print(inv_X)
print(inv_X.shape)
print('Row: %d' % data.shape[0])
print('Col: %d' % data.shape[0])

[[ 0.14285714 -0.57142857  0.42857143]
 [ 0.92857143  0.78571429 -1.21428571]
 [-0.28571429  0.14285714  0.14285714]]
(3, 3)
Row: 3
Col: 3


In [91]:
# reshaping Array
# reshape 1D to 2D array

data = array([11, 22, 33, 44, 55])
print(data)
print(data.shape)

data = data.reshape((data.shape[0], 1))
print(data)
print(data.shape)

[11 22 33 44 55]
(5,)
[[11]
 [22]
 [33]
 [44]
 [55]]
(5, 1)


In [94]:
# 2D to 3 D array:
data = array([
    [11, 22, 33],
    [44, 55, 66],
    [55, 66, 77]
])
print(data.shape)
data = data.reshape(data.shape[0], data.shape[1], 1)
print(data)
print(data.shape)

(3, 3)
[[[11]
  [22]
  [33]]

 [[44]
  [55]
  [66]]

 [[55]
  [66]
  [77]]]
(3, 3, 1)


In [95]:
# Array broadcasting.
# To allow array arithmatic between arrays with a different shape or size. It solve the problem of airthmatic between arrays of differing shapes by in effect replicating the smaller array along the last mismatched dimension.
# Broadcasting with scalar and One dimension array.
a = array([1, 2, 3])
b = 9
c = a + b
print(c)
print(c.shape)


[10 11 12]
(3,)


In [96]:
# Broadcasting with scalar and two dimension array
A = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

b = 9
res = A + b
print(res)
print(res.shape)

[[10 11 12]
 [13 14 15]
 [16 17 18]]
(3, 3)


In [97]:
# errors and exceptions

In [103]:
b = array([2, 4, 6])
print(b.shape)
res = A + b
print(res)
print(res.shape)

(3,)
[[ 3  6  9]
 [ 6  9 12]
 [ 9 12 15]]
(3, 3)


In [102]:
# Broadcasting limitations:
# Broadcasting can only be performed when the shape of each dimension in the arrays are equal or one has the dimension size of 1.
# e.g (3 X 3) and (3, 1) or (3 X 3) and (1, 3)
# what is not correct 
# e.g (3 X 3) and (1, 2)
A  = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(A.shape)
b = array([2, 4])
print(b.shape)
res = A + b # this will not work as b's dimension shape are not matching with A's one


(3, 3)
(2,)


ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

# Vector Norms:
# Vector length

In [ ]:
# Length of a vector is a non-negative number that describes the extent of the vector in space, and is sometimes referred to as the vector's magnitude or the norm.
# Length of a vector is always a positive number, except for a vector of all zero values. 
# it is calculated using some measure that summarize the distance of vetor from the orgin of the vector space. 
# For e.g vector space for a vector with 3 elements is (0,0,0)