In [1]:
import numpy as np

In [2]:
A = np.array([[2,1,1], [3, 2, 1], [2, 1, 2]])

In [3]:
A


array([[2, 1, 1],
       [3, 2, 1],
       [2, 1, 2]])

In [4]:
np.linalg.inv(A)

array([[ 3., -1., -1.],
       [-4.,  2.,  1.],
       [-1.,  0.,  1.]])

In [18]:
B1 = np.array([[2, -2], [1, 1]])
B2 = np.array([[3, -3], [2, 2]])
invB = np.linalg.inv(B2)
M = invB @ B1
print(M)

[[ 0.58333333 -0.08333333]
 [-0.08333333  0.58333333]]


In [22]:
older_basis = np.array([[1,0],[0,1]])
inv_basis = np.linalg.inv(older_basis)
alien = inv_basis @ np.array([-3, 12])
alien

array([-3., 12.])

In [36]:
B1 = np.array([[1,3,4,2],[3,2,4,1],[1,2,3,4],[3,2,1,1]])

In [37]:
B1

array([[1, 3, 4, 2],
       [3, 2, 4, 1],
       [1, 2, 3, 4],
       [3, 2, 1, 1]])

In [38]:
B2 = np.array([[1,1,2,3], [3,3,2,1], [1,2,2,3], [1,2,2,3], [1,2,2,1]])
B2

array([[1, 1, 2, 3],
       [3, 3, 2, 1],
       [1, 2, 2, 3],
       [1, 2, 2, 3],
       [1, 2, 2, 1]])

In [39]:
b2inv = np.linalg.inv(B2.T)

LinAlgError: Last 2 dimensions of the array must be square

In [40]:
k = np.array([[3, 8],[1, -16]])
k

array([[  3,   8],
       [  1, -16]])

In [41]:
invK = np.linalg.inv(k)
invK

array([[ 0.28571429,  0.14285714],
       [ 0.01785714, -0.05357143]])

In [42]:
std = np.array([[3], [2]])
std

array([[3],
       [2]])

In [44]:
invK.T @ std

array([[0.89285714],
       [0.32142857]])

In [45]:
cv = np.array([[2, 1], [3, 2], [2, 1], [5, 1]])

In [46]:
cv

array([[2, 1],
       [3, 2],
       [2, 1],
       [5, 1]])

In [47]:
cv.T


array([[2, 3, 2, 5],
       [1, 2, 1, 1]])

In [49]:
np.cov(cv.T)

array([[2.  , 0.  ],
       [0.  , 0.25]])

In [50]:
A = np.array([[5.6, 2.8], [2.8, 1.4]])


In [51]:
np.linalg.eig(A)

(array([7., 0.]),
 array([[ 0.89442719, -0.4472136 ],
        [ 0.4472136 ,  0.89442719]]))