In [1]:
import numpy as np
import pandas as pd

In [25]:
ipl18 = pd.DataFrame({'Team': ['SRH', 'CSK', 'KKR', 'RR', 'MI', 'RCB', 'KXIP', 'DD'],
                         'Matches': [14, 14, 14, 14, 14, 14, 14, 14],
                         'Won': [9, 9, 8, 7, 6, 6, 6, 5],
                         'Lost': [5, 5, 6, 7, 8, 8, 8, 9],
                         'Tied': [0, 0, 0, 0, 0, 0, 0, 0],
                         'N/R': [0, 0, 0, 0, 0, 0, 0, 0],
                         'Points': [18, 18, 16, 14, 12, 12, 12, 10],
                         'NRR': [0.284, 0.253, -0.070, -0.250, 0.317, 0.129, -0.502, -0.222],
                         'For': [2230, 2488, 2363, 2130, 2380, 2322, 2210, 2297],
                         'Against': [2193, 2433, 2425, 2141, 2282, 2383, 2259, 2304]},
                         index = range(1,9)
                    )

team_left = ipl18.loc[(ipl18['NRR'] > 0) & (ipl18['For']> ipl18['Against'])]
team_left

Team  Matches  Won  Lost  Tied  N/R  Points    NRR   For  Against
1  SRH       14    9     5     0    0      18  0.284  2230     2193
2  CSK       14    9     5     0    0      18  0.253  2488     2433
5   MI       14    6     8     0    0      12  0.317  2380     2282

In [28]:
ipl17 = pd.DataFrame({'Team': ['MI', 'RPS', 'SRH', 'KKR', 'KXIP', 'DD', 'GL', 'RCB'],
                         'Matches': [14, 14, 14, 14, 14, 14, 14, 14],
                         'Won': [10, 9, 8, 8, 7, 6, 4, 3],
                         'Lost': [4, 5, 5, 6, 7, 8, 10, 10],
                         'Tied': [0, 0, 0, 0, 0, 0, 0, 0],
                         'N/R': [0, 0, 1, 0, 0, 0, 0, 1],
                         'Points': [20, 18, 17, 16, 14, 12, 8, 7],
                         'NRR': [0.784, 0.176, 0.469, 0.641, 0.123, -0.512, -0.412, -1.299],
                         'For': [2407, 2180, 2221, 2329, 2207, 2219, 2406, 1845],
                         'Against': [2242, 2165, 2118, 2300, 2229, 2255, 2472, 2033]},
                         index = range(1,9)
                    )

ipl17

Team  Matches  Won  Lost  Tied  N/R  Points    NRR   For  Against
1    MI       14   10     4     0    0      20  0.784  2407     2242
2   RPS       14    9     5     0    0      18  0.176  2180     2165
3   SRH       14    8     5     0    1      17  0.469  2221     2118
4   KKR       14    8     6     0    0      16  0.641  2329     2300
5  KXIP       14    7     7     0    0      14  0.123  2207     2229
6    DD       14    6     8     0    0      12 -0.512  2219     2255
7    GL       14    4    10     0    0       8 -0.412  2406     2472
8   RCB       14    3    10     0    1       7 -1.299  1845     2033

In [33]:
combined_stats = pd.merge(ipl17, ipl18, how='inner', on = 'Team')
combined_stats

Team  Matches_x  Won_x  Lost_x  Tied_x  N/R_x  Points_x  NRR_x  For_x  \
0    MI         14     10       4       0      0        20  0.784   2407   
1   SRH         14      8       5       0      1        17  0.469   2221   
2   KKR         14      8       6       0      0        16  0.641   2329   
3  KXIP         14      7       7       0      0        14  0.123   2207   
4    DD         14      6       8       0      0        12 -0.512   2219   
5   RCB         14      3      10       0      1         7 -1.299   1845   

   Against_x  Matches_y  Won_y  Lost_y  Tied_y  N/R_y  Points_y  NRR_y  For_y  \
0       2242         14      6       8       0      0        12  0.317   2380   
1       2118         14      9       5       0      0        18  0.284   2230   
2       2300         14      8       6       0      0        16 -0.070   2363   
3       2229         14      6       8       0      0        12 -0.502   2210   
4       2255         14      5       9       0      0        10 -0.222   2297   
5       2033         14      6       8       0      0        12  0.129   2322   

   Against_y  
0       2282  
1       2193  
2       2425  
3       2259  
4       2304  
5       2383

In [38]:
combined_stats['Matches']= combined_stats['Matches_x'] + combined_stats['Matches_y']
combined_stats['Won'] = combined_stats['Won_x'] + combined_stats['Won_y']
combined_stats['Point'] = combined_stats['Points_x'] + combined_stats['Points_y']
combined_stats

Team  Matches_x  Won_x  Lost_x  Tied_x  N/R_x  Points_x  NRR_x  For_x  \
0    MI         14     10       4       0      0        20  0.784   2407   
1   SRH         14      8       5       0      1        17  0.469   2221   
2   KKR         14      8       6       0      0        16  0.641   2329   
3  KXIP         14      7       7       0      0        14  0.123   2207   
4    DD         14      6       8       0      0        12 -0.512   2219   
5   RCB         14      3      10       0      1         7 -1.299   1845   

   Against_x  ...  Lost_y  Tied_y  N/R_y  Points_y  NRR_y  For_y  Against_y  \
0       2242  ...       8       0      0        12  0.317   2380       2282   
1       2118  ...       5       0      0        18  0.284   2230       2193   
2       2300  ...       6       0      0        16 -0.070   2363       2425   
3       2229  ...       8       0      0        12 -0.502   2210       2259   
4       2255  ...       9       0      0        10 -0.222   2297       2304   
5       2033  ...       8       0      0        12  0.129   2322       2383   

   Matches  Won  Point  
0       28   16     32  
1       28   17     35  
2       28   16     32  
3       28   13     26  
4       28   11     22  
5       28    9     19  

[6 rows x 22 columns]

In [40]:
final_stats = combined_stats.loc[:,['Team','Matches', 'Won' ,'Point']]
final_stats

Team  Matches  Won  Point
0    MI       28   16     32
1   SRH       28   17     35
2   KKR       28   16     32
3  KXIP       28   13     26
4    DD       28   11     22
5   RCB       28    9     19

In [41]:
final_stats.describe()

Matches        Won      Point
count      6.0   6.000000   6.000000
mean      28.0  13.666667  27.666667
std        0.0   3.204164   6.345602
min       28.0   9.000000  19.000000
25%       28.0  11.500000  23.000000
50%       28.0  14.500000  29.000000
75%       28.0  16.000000  32.000000
max       28.0  17.000000  35.000000

In [42]:
final_stats.max()

Team       SRH
Matches     28
Won         17
Point       35
dtype: object

In [54]:
import numpy as np 

# Given array
a = np.array([[4, 3, 1], [5, 7, 0], [9, 9, 3], [8, 2, 4]])

# Read the values of m and n
m = 0
n = 2


# Write your code for swapping here
t = np.copy(a[m])
k = np.copy(a[n])
a[m] = k
a[n] = t
# Print the array after swapping
print(a)

[[9 9 3]
 [5 7 0]
 [4 3 1]
 [8 2 4]]


In [60]:
pp = np.ones([3, 3], dtype = np.int)
pp[1: -1, 1: -1 ] = 0
pp

[[1 1 1]]


array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])